import ClientProviders from "./components/ClientProviders/ClientProviders";
import { CategoriesMenu } from "./components/CategoriesMenu/CategoriesMenu";
import { CurrencySelector } from "./components/CurrencySelector/CurrencySelector";
import { Footer } from "./components/Footer/Footer";
import { IconMenu } from "./components/IconMenu/IconMenu";
import { Logo } from "./components/Logo/Logo";
import { MainContent } from "./components/MainContent/MainContent";
import { MainMenu } from "./components/MainMenu/MainMenu";
import { TopBar } from "./components/TopBar/TopBar";
import "./styles/globals.css";
import "./styles/theme.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Fashon contemporary shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body>
        <ClientProviders>
          <MainContent>
            <TopBar>
              <MainMenu />
              <Logo />
              <div>
                <CurrencySelector />
                <IconMenu />
              </div>
            </TopBar>
            <CategoriesMenu />
            {children}
          </MainContent>
        </ClientProviders>
        <Footer />
      </body>
    </html>
  );
}
